version: '3.9'

services:
  webapp:
    image: lwglg/nld-img-heat-map-webapp:latest
    container_name: nld-img-heat-map-webapp
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/webapp/Dockerfile
    privileged: true
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    command: [ "python", "-m", "webapp.main" ]
    ports:
      - "8001:8001"
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - ../../../webapp:/usr/local/nld-img-heat-map/webapp
      - ../../../resources/static:/usr/local/nld-img-heat-map/static
      - ../../../img_analysis_data:/usr/local/nld-img-heat-map/img_analysis_data
      - './webapp/webapp-config.yml:/usr/local/nld-img-heat-map/webapp-config.yml'
    env_file:
      - ./webapp/.webapp.env
    restart: always
    networks:
      - default-net

  database:
    container_name: nld-img-heat-map-db
    image: lwglg/nld-img-heat-map-db:latest
    build:
      context: ../../..
      dockerfile: ./infra/docker/develop/database/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./database/.database.env
    volumes:
      - pgsql-data:/var/lib/pgsql/pgdata
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - "5000:5000"
    networks:
      - default-net

networks:
  default-net:
    driver: bridge

volumes:
  pgsql-data:
